# -*- coding: utf-8 -*-
"""LoRaWAN Geolocation with Kalman Filter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0N6A7Vsr9ECkAjFKjIGMJ4LtJrjCWtU

For a high-quality manual deployment, we must treat geolocation as a **sensor fusion** problem. We will use a **Weighted Least Squares (WLS)** solver to combine RSSI and TDOA, and then pass the results through a **Kalman Filter** to smooth out the noise.

### 1. Prerequisites

You need `paho-mqtt`, `numpy`, and `scipy`.

```bash
pip install paho-mqtt numpy scipy

```

### 2. Comprehensive Geolocation Script

This script handles the MQTT connection, extracts "fine timestamps" (if available) or GPS timestamps, performs the hybrid calculation, and applies a Kalman Filter for smoothing.
"""

import json
import time
import numpy as np
from scipy.optimize import minimize
import paho.mqtt.client as mqtt

# --- CONFIGURATION ---
TTN_USERNAME = "fst-scm-b195-tst@ttn"
TTN_PASSWORD = "NNSXS.NXSXUR2AKM3DFD47EF5ZOQ4ADXLNQJ2NJ5HUWDY.XVZ4PH25CSHBRER4J4GKF47EPVL6AYXH3AJG7YIEI4MVBNG3G5VA"
MQTT_BROKER = "eu1.cloud.thethings.network"
MQTT_PORT = 8883

# --- PHYSICAL CONSTANTS ---
C = 299792458  # Speed of light (m/s)
N = 2.8        # Path loss exponent (2.0=free space, 3.0=urban)
A = -35        # Reference RSSI at 1 meter

# --- KALMAN FILTER STATE ---
class KalmanFilter:
    def __init__(self):
        self.P = np.eye(2) * 1000  # Initial uncertainty
        self.Q = np.eye(2) * 0.001 # Process noise (how much the sensor moves)
        self.R = np.eye(2) * 0.1   # Measurement noise
        self.state = None          # [lat, lon]

    def update(self, measurement):
        if self.state is None:
            self.state = measurement
            return self.state

        # Prediction
        P_prior = self.P + self.Q

        # Update
        K = P_prior @ np.linalg.inv(P_prior + self.R)
        self.state = self.state + K @ (measurement - self.state)
        self.P = (np.eye(2) - K) @ P_prior
        return self.state

kf_instances = {} # Dictionary to hold a KF for every device_id

# --- CORE MATH: HYBRID SOLVER ---
def calculate_distance_rssi(rssi):
    """Log-distance path loss model: returns distance in meters."""
    return 10 ** ((A - rssi) / (10 * N))

def hybrid_loss_func(coords, gateways):
    lat, lon = coords
    total_error = 0

    # Reference gateway for TDOA (usually the first one)
    ref_gw = gateways[0]
    ref_dist = np.sqrt((lat - ref_gw['lat'])**2 + (lon - ref_gw['lon'])**2) * 111320 # approx meters

    for i, gw in enumerate(gateways):
        # Euclidean distance in meters
        dist = np.sqrt((lat - gw['lat'])**2 + (lon - gw['lon'])**2) * 111320

        # 1. RSSI Loss
        rssi_dist = calculate_distance_rssi(gw['rssi'])
        rssi_loss = (dist - rssi_dist)**2

        # 2. TDOA Loss
        # time_diff is in seconds, multiplied by speed of light = distance diff in meters
        if i > 0 and 'toa' in gw and 'toa' in ref_gw:
            observed_diff = (gw['toa'] - ref_gw['toa']) * C
            expected_diff = dist - ref_dist
            tdoa_loss = (observed_diff - expected_diff)**2
        else:
            tdoa_loss = 0

        # 3. Hybrid Weighting & SNR Thresholding
        # Trust TDOA more (weight 10.0) than RSSI (weight 1.0)
        # Penalize low SNR signals (below -15dB)
        weight = 1.0 if gw['snr'] > -15 else 0.1
        total_error += weight * (rssi_loss + (tdoa_loss * 10.0))

    return total_error

# --- MQTT HANDLERS ---
def on_message(client, userdata, msg):
    data = json.loads(msg.payload.decode())
    dev_id = data['end_device_ids']['device_id']
    rx_metadata = data.get('uplink_message', {}).get('rx_metadata', [])

    gateways = []
    for gw in rx_metadata:
        # Extract location and timestamp (try fine_timestamp first, then gps_time)
        loc = gw.get('location', {})
        if not loc: continue

        # Convert GPS time string to float unix seconds if available
        toa = None
        if 'gps_time' in gw:
            from dateutil import parser
            toa = parser.parse(gw['gps_time']).timestamp()

        gateways.append({
            'lat': loc.get('latitude'),
            'lon': loc.get('longitude'),
            'rssi': gw.get('rssi'),
            'snr': gw.get('snr'),
            'toa': toa
        })

    if len(gateways) >= 3:
        # 1. Solver: Initial guess is the average of gateway positions
        init_guess = [np.mean([g['lat'] for g in gateways]), np.mean([g['lon'] for g in gateways])]
        res = minimize(hybrid_loss_func, init_guess, args=(gateways,), method='Nelder-Mead')
        raw_coords = res.x

        # 2. Smoothing: Apply Kalman Filter
        if dev_id not in kf_instances:
            kf_instances[dev_id] = KalmanFilter()

        smoothed_coords = kf_instances[dev_id].update(raw_coords)

        print(f"[{dev_id}] Raw: {raw_coords[0]:.5f}, {raw_coords[1]:.5f} | "
              f"Smoothed: {smoothed_coords[0]:.5f}, {smoothed_coords[1]:.5f}")

# --- CLIENT STARTUP ---
client = mqtt.Client()
client.username_pw_set(TTN_USERNAME, TTN_PASSWORD)
client.on_message = on_message
client.connect(MQTT_BROKER, MQTT_PORT)
client.subscribe("v3/+/devices/+/up")
client.loop_forever()

"""---

### Why this gives "Good Results"

#### 1. The Hybrid Weighting Strategy

TDOA is extremely precise but can "echo" or provide false intersections in dense urban areas. RSSI is imprecise but provides a physical boundary (a circle of probability). By combining them, RSSI prevents the TDOA calculation from snapping to an impossible location, while TDOA provides the fine-grained accuracy.

#### 2. SNR Thresholding (The Gatekeeper)

In the `hybrid_loss_func`, we check `if gw['snr'] > -15`. Low SNR usually indicates a multipath signal—one that bounced off a building before reaching the gateway. These signals have traveled further than the straight-line distance, which ruins your math. We drop their weight to $0.1$ so they don't corrupt the "clean" signals.

#### 3. Kalman Filtering (The Smoother)

A LoRaWAN sensor doesn't teleport. If one uplink calculates a position 50 meters away from the previous one, it's likely noise, not movement.

* **Process Noise ($Q$):** Set this based on how fast your device moves (e.g., higher for a car, lower for a stationary asset).
* **Measurement Noise ($R$):** Set this based on the expected error of your trilateration (usually 50–100m).

### A Note on TDOA Precision

In the script, I used `gw.get('gps_time')`. In TTN V3, some gateways provide a `fine_timestamp` field (an encrypted or nanosecond-resolution field). If your gateway supports it, replace the `toa` logic with that field for much higher accuracy. Without nanosecond precision, your TDOA component will have a very high error, and you should rely more heavily on the RSSI weight.
"""