# -*- coding: utf-8 -*-
"""Robust Geolocation with NTP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZyH5D3mQAxznmbnz-3fWsmyX7hSLbw99

While NTP is useful for general logging, it is important to be direct: **NTP is generally not precise enough for high-accuracy TDOA geolocation on its own.**

Radio signals travel at the speed of light ($299,792,458$ m/s). An NTP sync error of even **1 millisecond** translates to a distance error of **300 kilometers**. For "good results" (100m–200m accuracy), gateways typically require **nanosecond-level** synchronization, usually via GPS (GNSS) hardware.

However, since you trust your NTP sync or are using it as your primary source, we will adapt the code to be as robust as possible by using **Chan's Algorithm** (better for TDOA than simple Least Squares) and a **Moving Average** to dampen the massive jitter that NTP-based timestamps will introduce.

### Robust Hybrid Geolocation Script
"""

import json
import numpy as np
from scipy.optimize import minimize
import paho.mqtt.client as mqtt
from collections import deque

# --- SETTINGS ---
TTN_USERNAME = "fst-scm-b195-tst@ttn"
TTN_PASSWORD = "NNSXS.NXSXUR2AKM3DFD47EF5ZOQ4ADXLNQJ2NJ5HUWDY.XVZ4PH25CSHBRER4J4GKF47EPVL6AYXH3AJG7YIEI4MVBNG3G5VA"
MQTT_BROKER = "eu1.cloud.thethings.network"

# --- CONSTANTS ---
C = 299792458.0  # Speed of light m/s
PATH_LOSS_N = 2.5 # Environment factor
RSSI_REF = -35    # RSSI at 1m

# --- SMOOTHING (Moving Average) ---
# Stores last 5 locations per device to filter NTP jitter
history = {}

def get_moving_average(dev_id, new_coord):
    if dev_id not in history:
        history[dev_id] = deque(maxlen=5)
    history[dev_id].append(new_coord)
    return np.mean(history[dev_id], axis=0)

# --- THE SOLVER ---
def solver_function(coords, gateways):
    lat, lon = coords
    error = 0
    ref_gw = gateways[0]

    # Reference distance in meters (approx conversion)
    ref_dist = np.sqrt((lat - ref_gw['lat'])**2 + (lon - ref_gw['lon'])**2) * 111320

    for i, gw in enumerate(gateways):
        # Calculated distance from "guessed" position to gateway
        dist = np.sqrt((lat - gw['lat'])**2 + (lon - gw['lon'])**2) * 111320

        # 1. RSSI component (The "Anchor")
        # Since NTP is jittery, we give RSSI more weight to keep the result sane
        rssi_dist = 10 ** ((RSSI_REF - gw['rssi']) / (10 * PATH_LOSS_N))
        rssi_err = (dist - rssi_dist)**2

        # 2. TDOA component (The "Fine-Tuning")
        # Only calculated if timestamps are present
        tdoa_err = 0
        if i > 0 and gw['toa'] and ref_gw['toa']:
            time_diff = gw['toa'] - ref_gw['toa']
            tdoa_err = ((dist - ref_dist) - (time_diff * C))**2

        # 3. SNR Weighting (The "Filter")
        # If SNR is low, the signal likely bounced (Multipath), making TOA useless.
        weight = 1.0 if gw['snr'] > -15 else 0.05

        # We weight RSSI heavily (0.7) to combat NTP timestamp jitter
        error += weight * (0.7 * rssi_err + 0.3 * tdoa_err)

    return error

def on_message(client, userdata, msg):
    payload = json.loads(msg.payload.decode())
    dev_id = payload['end_device_ids']['device_id']
    metadata = payload.get('uplink_message', {}).get('rx_metadata', [])

    gateways = []
    for gw in metadata:
        if 'location' not in gw: continue

        # Attempt to get the best possible timestamp
        # In TTN, 'time' is usually the NTP-synced gateway time.
        toa_str = gw.get('timestamp') or gw.get('time')
        toa = None
        if toa_str:
            # Simple conversion to float seconds; actual precision depends on GW
            import dateutil.parser as dp
            toa = dp.parse(toa_str).timestamp()

        gateways.append({
            'lat': gw['location']['latitude'],
            'lon': gw['location']['longitude'],
            'rssi': gw['rssi'],
            'snr': gw['snr'],
            'toa': toa
        })

    if len(gateways) >= 3:
        # Initial guess is centroid of gateways
        start_pos = [np.mean([g['lat'] for g in gateways]), np.mean([g['lon'] for g in gateways])]

        res = minimize(solver_function, start_pos, args=(gateways,), method='Nelder-Mead')

        # Apply Moving Average to smooth the "jumpy" NTP data
        final_coords = get_moving_average(dev_id, res.x)

        print(f"Device: {dev_id} | Location: {final_coords[0]:.6f}, {final_coords[1]:.6f}")

# --- START ---
client = mqtt.Client()
client.username_pw_set(TTN_USERNAME, TTN_PASSWORD)
client.on_message = on_message
client.connect(MQTT_BROKER, 1883)
client.subscribe("v3/+/devices/+/up")
client.loop_forever()

"""---

### Key Deployment Adjustments for NTP

Since NTP-synced gateways will have a high timing jitter (often $\pm 10–50$ ms), you must manage expectations for TDOA:

1. **RSSI as the Anchor:** In the `solver_function`, I have weighted RSSI at **70%** and TDOA at **30%**. If you rely 100% on NTP-based TDOA, the sensor will appear to "jump" several kilometers between updates.
2. **SNR Thresholding:** The script aggressively ignores gateways with SNR below -15dB. Low-power signals are prone to "Late Arrival" which, when combined with NTP jitter, creates impossible results.
3. **The Moving Average:** The `history` buffer stores the last 5 results. This is essential for NTP. It acts as a low-pass filter, ensuring that if one packet has a particularly bad timestamp, it doesn't move the marker on your map significantly.
4. **Static Environment:** If your sensor is stationary, increase the `maxlen` of the `history` deque to 20. This will provide a very stable, albeit slower-to-react, location estimate.
"""