# -*- coding: utf-8 -*-
"""detailed Python script that covers the Summary of...

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7nwkPx9y9frEVlj25RsFzkKfG2TYcIK

To build a robust adaptive solver, the script needs to handle asynchronous data (gateways don't report at the exact same millisecond) and then choose the math based on the "Baseline" distance.

Here is a detailed implementation using `paho-mqtt` for data, `pyproj` for coordinate conversion, and `numpy` for the math.

### Prerequisites

You will need to install these libraries:
`pip install paho-mqtt pyproj numpy`

---

### The Adaptive Hybrid Solver
"""

import json
import time
import numpy as np
from pyproj import Transformer
import paho.mqtt.client as mqtt

# --- CONFIGURATION ---
MQTT_BROKER = "eu1.cloud.thethings.network"
MQTT_USER = "your-app-id@ttn"
MQTT_PASS = "NNSXS.YOUR_API_KEY"
TOPIC = "v3/+/devices/+/up"

# Settings for the solver
BASELINE_THRESHOLD_METERS = 100.0  # If GWs are closer than this, use Centroid
PATH_LOSS_EXPONENT = 3.0           # 2.0 = open space, 4.0 = thick city
SIGMA_RSSI = 5.0                   # Uncertainty factor for RSSI

# Coordinate Transformer: WGS84 (Lat/Lon) to UTM Zone 32N (Meters)
# Change 'epsg:32632' if your gateways are not in Central Europe
transformer_to_meters = Transformer.from_crs("epsg:4326", "epsg:32632", always_xy=True)
transformer_to_gps = Transformer.from_crs("epsg:32632", "epsg:4326", always_xy=True)

# Buffer to store metadata because gateways report at slightly different times
uplink_buffer = {}

def solve_weighted_centroid(gws):
    """
    Used when gateways are in the same building.
    Uses RSSI and SNR to find a 'probability center' between them.
    """
    total_w = 0
    sum_x = 0
    sum_y = 0

    for gw in gws:
        # Convert RSSI to linear weight. -60dBm is much stronger than -90dBm.
        # We also factor in SNR (Signal to Noise Ratio).
        weight = (10 ** (gw['rssi'] / 20)) * max(0.1, gw['snr'])

        sum_x += gw['x'] * weight
        sum_y += gw['y'] * weight
        total_w += weight

    return sum_x / total_w, sum_y / total_w

def solve_trilateration(gws):
    """
    Used when gateways are far apart.
    Uses the RSSI distance circles to find an intersection.
    """
    # For 2 gateways, the intersection of two circles is two points.
    # We pick the one weighted closer to the gateway with the better SNR.
    x1, y1, r1 = gws[0]['x'], gws[0]['y'], 10**(((-30) - gws[0]['rssi'])/(10*PATH_LOSS_EXPONENT))
    x2, y2, r2 = gws[1]['x'], gws[1]['y'], 10**(((-30) - gws[1]['rssi'])/(10*PATH_LOSS_EXPONENT))

    # Simple midpoint weighting as a fallback for 2-point trilateration
    d = np.sqrt((x2-x1)**2 + (y2-y1)**2)
    a = (r1**2 - r2**2 + d**2) / (2*d)
    h = np.sqrt(max(0, r1**2 - a**2))

    x_point = x1 + a*(x2-x1)/d
    y_point = y1 + a*(y2-y1)/d

    return x_point, y_point

def process_uplink(device_id, metadata):
    if len(metadata) < 2:
        return # Need at least 2 gateways for this math

    # 1. Convert all GW coordinates to Meters
    for gw in metadata:
        loc = gw.get('location', {})
        gw['x'], gw['y'] = transformer_to_meters.transform(loc['longitude'], loc['latitude'])

    # 2. Calculate Baseline
    dist = np.sqrt((metadata[0]['x'] - metadata[1]['x'])**2 + (metadata[0]['y'] - metadata[1]['y'])**2)

    print(f"--- Processing {device_id} ---")
    print(f"Gateway Baseline: {dist:.2f} meters")

    # 3. Choose Logic
    if dist < BASELINE_THRESHOLD_METERS:
        print("Mode: Same Building (Weighted Centroid)")
        res_x, res_y = solve_weighted_centroid(metadata)
    else:
        print("Mode: Wide Aperture (Trilateration)")
        res_x, res_y = solve_trilateration(metadata)

    # 4. Convert back to GPS
    final_lon, final_lat = transformer_to_gps.transform(res_x, res_y)
    print(f"Result: Lat {final_lat:.6f}, Lon {final_lon:.6f}\n")

# --- MQTT CALLBACKS ---
def on_message(client, userdata, msg):
    payload = json.loads(msg.payload)
    dev_id = payload['end_device_ids']['device_id']
    f_cnt = payload['uplink_message']['f_cnt']
    metadata = payload['uplink_message'].get('rx_metadata', [])

    # Key is DeviceID + Frame Counter to ensure we group reports of the same packet
    key = f"{dev_id}_{f_cnt}"

    if key not in uplink_buffer:
        uplink_buffer[key] = metadata
        # Wait 0.5s for other gateways to report before solving
        time.sleep(0.5)
        process_uplink(dev_id, uplink_buffer[key])
        del uplink_buffer[key]

# --- START SCRIPT ---
client = mqtt.Client()
client.username_pw_set(MQTT_USER, MQTT_PASS)
client.on_message = on_message
client.connect(MQTT_BROKER, 1883, 60)
client.subscribe(TOPIC)
client.loop_forever()

"""---

### How this script works

1. **The "Key" Strategy:** LoRaWAN gateways often report to the network server at slightly different times (due to internet latency). The script uses the `f_cnt` (Frame Counter) to make sure it is grouping the metadata from the **exact same uplink packet**.
2. **The Coordinate Shift:** Calculating distance using Latitude/Longitude is mathematically heavy and prone to errors. By converting to **UTM (Meters)** first, we can use simple geometry.
3. **The Threshold Switch:**
* **Under 100m:** It assumes the gateways are in the same building. It uses `solve_weighted_centroid`. This prevents the "Trilateration" math from breaking when the circles perfectly overlap.
* **Over 100m:** It treats them as distinct points in a city and uses the geometric intersection of their signal radii.


4. **SNR Weighting:** In the building scenario, we don't just look at RSSI. We multiply the weight by the **SNR**. If Gateway A has a clear line of sight (High SNR) and Gateway B is behind a concrete wall (Low SNR), the script will correctly "pull" the estimated location toward Gateway A.

### Limitations to remember

* **Verticality:** This script calculates a 2D position. If your gateways are on the 1st floor and 10th floor of the same building, the "Baseline" will look small, but the RSSI will vary wildly.
* **Path Loss Exponent:** The `PATH_LOSS_EXPONENT` is currently set to `3.0
"""